"""Opens a pull request with the generated documentation.

# GITHUB INTEGRATION: PR Writer
The only module that writes to GitHub. Called by the runner exclusively
AFTER verification and guardrails have passed — unverified docs can never
reach a pull request.
"""

from github import GithubException

from github_integration.client import GitHubIntegrationError, get_repo


def _slug(name: str) -> str:
    cleaned = "".join(c if c.isalnum() or c in "-_" else "_" for c in name.strip())
    return cleaned or "section"


def create_docs_pr(
    repo_full_name: str,
    docs: dict[str, str],
    run_id: str,
    confidence: float | None = None,
    files_documented: list[str] | None = None,
) -> str:
    """Create a branch, commit each doc section, and open a PR.

    Branch: docagent/run-{run_id[:8]}; each docs key becomes
    docs/generated/{slug}.md. Returns the PR URL.
    """
    if not docs:
        raise GitHubIntegrationError("No doc sections were staged; nothing to open a PR for.")

    repo = get_repo(repo_full_name)
    short_id = run_id[:8]
    branch_name = f"docagent/run-{short_id}"

    try:
        base = repo.get_branch(repo.default_branch)
        repo.create_git_ref(ref=f"refs/heads/{branch_name}", sha=base.commit.sha)

        written_paths: list[str] = []
        for section_name, content in docs.items():
            path = f"docs/generated/{_slug(section_name)}.md"
            message = f"docs: add {section_name} [{short_id}]"
            try:
                # The file may already exist on the default branch from a
                # previous DocAgent run — update instead of create.
                existing = repo.get_contents(path, ref=branch_name)
                repo.update_file(path, message, content, existing.sha, branch=branch_name)
            except GithubException:
                repo.create_file(path, message, content, branch=branch_name)
            written_paths.append(path)

        body_lines = [
            "Documentation generated by **DocAgent Harness**.",
            "",
            "### Files documented",
            *[f"- `{f}`" for f in (files_documented or [])],
            "",
            "### Doc sections in this PR",
            *[f"- `{p}`" for p in written_paths],
            "",
            f"**Verification confidence:** {confidence:.2f}" if confidence is not None else "",
            f"**Run ID:** `{run_id}`",
            "",
            f"Observability: `GET /runs` on the DocAgent server (look up run `{short_id}`).",
            "",
            "_Every section in this PR passed the harness's hallucination check,",
            "self-critique verification, and code-provenance guardrails._",
        ]
        pr = repo.create_pull(
            title=f"docs: AI-generated documentation [{short_id}]",
            body="\n".join(line for line in body_lines if line is not None),
            head=branch_name,
            base=repo.default_branch,
        )
        return pr.html_url
    except GithubException as exc:
        raise GitHubIntegrationError(
            f"Failed to open docs PR on {repo_full_name}: {exc}", status_code=502
        ) from exc
